docker load --input dynamodb.iso
docker load --input meerkatdemo_abacus.iso
docker load --input meerkatdemo_api.iso
docker load --input meerkatdemo_auth.iso
docker load --input meerkatdemo_frontend.iso
docker load --input meerkatdemo_hermes.iso
docker load --input meerkatdemo_nginx.iso
docker load --input postgis.iso
docker load --input rabbitmq.iso